FROM asuracodes/work:cm4
# FROM armv7/armhf-debian
# FROM wpilib/raspbian-cross-ubuntu

# ARG UBUNTU=22.04
# FROM wpilib/ubuntu-base:${UBUNTU}

RUN apt update -y
# add c/c++
RUN apt install -y cmake
RUN apt install -y gcc-arm-linux-gnueabihf
RUN apt install -y g++-arm-linux-gnueabihf
RUN apt install -y sqlite3 libsqlite3-dev
RUN apt install -y libspdlog-dev
RUN apt install -y mosquitto mosquitto-clients libmosquitto-dev