FROM asuracodes/work:cm4

# make it up to date
RUN apt update && apt install -y

# add c/c++
RUN apt install -y cmake
RUN apt install -y gcc-arm-linux-gnueabihf
RUN apt install -y g++-arm-linux-gnueabihf
RUN apt install -y sqlite3 libsqlite3-dev
RUN apt install -y libspdlog-dev
# RUN sudo apt install -y git
# RUN git clone https://github.com/eclipse/paho.mqtt.c.git
# RUN cd paho.mqtt.c
# RUN git checkout v1.3.8
# RUN cmake -Bbuild -H. -DPAHO_ENABLE_TESTING=OFF -DPAHO_BUILD_STATIC=ON -DPAHO_WITH_SSL=ON -DPAHO_HIGH_PERFORMANCE=ON
# RUN sudo cmake --build build/ --target install
# RUN sudo ldconfig